apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-aetherroyale-frontend-deployment
  namespace: staging-aetherroyale-frontend
  labels:
    app: staging-aetherroyale-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-aetherroyale-frontend
  template:
    metadata:
      labels:
        app: staging-aetherroyale-frontend
    spec:
      containers:
        - name: staging-aetherroyale-frontend
          image: corentin35/aetherroyale-website-frontend:staging-${TAG_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NUXT_PUBLIC_BASE_URL_API
              value: "https://staging.api.aetherroyale.crzgames.com"
            - name: NUXT_PUBLIC_NODE_ENV
              value: "staging"
            - name: NUXT_PUBLIC_SITE_URL
              value: "https://staging.aetherroyale.crzgames.com"
            - name: NUXT_SITE_ENV
              value: "staging"
            - name: NUXT_SITE_NAME
              value: "Aether Royale"
          resources:
            requests:
              cpu: '100m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
      imagePullSecrets:
        - name: regcred
